---
- name: test
  gather_facts: false
  hosts: webservers
  vars:
    ansible_ssh_user: user
  become: yes

  tasks:
  - name: "Install nginx via apt"
    ansible.builtin.apt:
      name: "nginx"
      state: "latest"
      update_cache: true
  - name: "Start a nginx with systemd"
    systemd:
      name: "nginx"
      state: started
  - name: "Enable nginx service"
    systemd:
      name: "nginx.service"
      enabled: true