- name: Check HTTP page via jump host
  hosts: bastion
  vars:
    ansible_ssh_user: user
  gather_facts: false
  tasks:
    - name: Check HTTP page on web-a
      ansible.builtin.uri:
        url: "http://10.0.1.17"
        method: GET
      register: web_a_result
    - name: Print result
      ansible.builtin.debug:
        msg: "HTTP status for web-a {{ web_a_result.status }}"
    - name: Check HTTP page on web-b
      ansible.builtin.uri:
        url: "http://10.0.2.26"
        method: GET
      register: web_b_result
    - name: Print result
      ansible.builtin.debug:
        msg: "HTTP status for web-b {{ web_b_result.status }}"